[package]
authors = ["Advanca Authors"]
edition = "2018"
name = "advanca-client"
license = "GPL-3.0"
version = "0.4.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grpcio   = { rev = "249e21b3593a8bdd58429d2552b9ab72d6d46526", git = "https://github.com/tikv/grpc-rs.git", default-features = false, features = ["openssl", "protobuf-codec"] }
clang-sys = "=0.28.1"
env_logger = "0.7.0"
futures = "0.1.29"
hyper = "0.12.35"
jsonrpc-core-client = { version = "14.0.3", features = ["http", "ws"] }
log = "0.4.8"
hex = "0.4.2"
error-chain = "0.12"
serde = { version = "1.0", features = ["derive"]}
serde_cbor = "0.11.1"
serde_json = "1"
protobuf = "=2.8.1"
structopt = "0.3"

node-primitives = { git = "https://github.com/paritytech/substrate", rev = "00a400f82539e2f78e8ddbcd98aea512c87c5f3c"}
sc-rpc = { git = "https://github.com/paritytech/substrate", rev = "00a400f82539e2f78e8ddbcd98aea512c87c5f3c"}
sp-core = { git = "https://github.com/paritytech/substrate", rev = "00a400f82539e2f78e8ddbcd98aea512c87c5f3c"}
sp-runtime = { git = "https://github.com/paritytech/substrate", rev = "00a400f82539e2f78e8ddbcd98aea512c87c5f3c"}
sp-keyring = { git = "https://github.com/paritytech/substrate", rev = "00a400f82539e2f78e8ddbcd98aea512c87c5f3c"}
node-runtime = { git = "https://github.com/paritytech/substrate", rev = "00a400f82539e2f78e8ddbcd98aea512c87c5f3c"}

sgx_crypto_helper = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_types         = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_ucrypto       = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git" }

advanca-crypto-types = { tag = "v0.3.0", git = "https://github.com/advanca/advanca-sgx-helper" }
advanca-crypto       = { tag = "v0.3.0", git = "https://github.com/advanca/advanca-sgx-helper", features=["std_env"] }
advanca-core         = { tag = "v0.2.0", git = "https://github.com/advanca/advanca-node/" }
advanca-runtime      = { tag = "v0.2.0", git = "https://github.com/advanca/advanca-node/" }

worker-protos-std    = { path = "../worker-protos/worker-protos-std" }

[dependencies.substrate-api-client]
git = "https://github.com/advanca/substrate-api-client"
rev = "1231a987dcfe5610ddbd32ada6f95aecc4f90ec9"

[dependencies.codec]
package = "parity-scale-codec"
version = "1.0.0"

[dependencies.substrate-api]
path = "../substrate-api"
