[package]
authors = ["Advanca Authors"]
edition = "2018"
license = "GPL-3.0"
name = "substrate-api"
version = "0.3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7.0"
log = "0.4.8"
hex = "0.4.2"
async-std = { version = "1.6.2", features = ["attributes"] }

sp-core         = { tag = "v2.0.0-rc5+2", git = "https://github.com/paritytech/substrate" }
sp-runtime      = { tag = "v2.0.0-rc5+2", git = "https://github.com/paritytech/substrate" }
pallet-balances = { tag = "v2.0.0-rc5+2", git = "https://github.com/paritytech/substrate" }

advanca-node-primitives = { rev = "dc13cadb1e375223c85a22c1fd404b951b6d869a", git = "https://github.com/advanca/advanca-node" }

[dependencies.codec]
package = "parity-scale-codec"
version = "1.3.0"

[dependencies.substrate-subxt]
git = 'https://github.com/advanca/substrate-subxt'
rev = '9641da555dfa43190069c47ab02ff69e913b08b5'

[dev-dependencies]
sp-keyring = { tag = "v2.0.0-rc5+2", git = "https://github.com/paritytech/substrate" }
